### ISSUE TITLE
VersionedCollector only deletes rows from base class tables

### ISSUE THREAD

**Issue by matthewrayner** [brettt89/silverstripe-garbage-collector#16]
`VersionedCollector->getTableNameForClass()` uses `DataObjectSchema->baseDataTable` the base table not `DataObjectSchema->tableName`.

So it ends up adding duplicate values to the class list in `VersionedCollector->getTablesListForClass()` when it's creating the `VersionedCollector->deleteVersionsQuery()` which in turn gets passed on to the `SQLExpressionProcessor` which causes an error.

The best example of this is if you have a record with the class of `SilverStripe\Assets\Image` it will add two `SilverStripe\Assets\File` tables.

**Comment by michalkleiner** [comment]
Thanks for catching this @matthewrayner.
It's probably not covered by tests so adding a test and fixing the issue would be great.

**Comment by matthewrayner** [comment]
I'm sorry, I would open a pull request but I'm not familiar with unit tests. 
Hopefully I have provided enough information for someone else to fix it.

**Comment by michalkleiner** [comment]
@matthewrayner fixed and released as [1.2.0](https://github.com/brettt89/silverstripe-garbage-collector/releases/tag/1.2.0).
