### ISSUE TITLE
VersionedCollector doesn't collect records for all classes

### ISSUE THREAD

**Issue by matthewrayner** [brettt89/silverstripe-garbage-collector#19]
VersionedCollector stops collecting records when one of classes has no versions to delete causing it to not continue looping through all the classes.

https://github.com/brettt89/silverstripe-garbage-collector/blob/d9a539e92ea8428b87b157f22b032d2e5beaf25f/src/Collectors/VersionedCollector.php#L102

**Comment by michalkleiner** [comment]
Good find @matthewrayner, that probably should be a `continue` instead of a `return`.
