### ISSUE TITLE
Production Ready

### ISSUE THREAD

**Issue by brettt89** [brettt89/silverstripe-garbage-collector#2]
This issue was raised to track the Production Ready issues that may be blocking users from using this module within Production for their Applications.

Tasks

- [x] Remove "Warning" from `README.md`
- [x] Test on actual applications thoroughly
- [x] Determine minimum requirements and define
- [x] Update `composer.json` to have version control that allows for earliest possibly dependencies
- [x] Performance Testing

**Comment by brettt89** [comment]
@mfendeksilverstripe Any other suggestions / changes / features you would recommend to add to this list before making a release?

**Comment by mfendeksilverstripe** [comment]
I think we are good for now @brettt89 , feel free to go ahead with a release 👍
