### ISSUE TITLE
Call to undefined method SilverStripe\ORM\Connect\MySQLStatement::next() on VersionedCollector

### ISSUE THREAD

**Issue by elliot-sawyer** [brettt89/silverstripe-garbage-collector#39]
Call to undefined method SilverStripe\ORM\Connect\MySQLStatement::next() {"exception":"[object] (Error(code: 0): Call to undefined method SilverStripe\\ORM\\Connect\\MySQLStatement::next() at /app/vendor/brettt89/silverstripe-garbage-collector/src/Collectors/VersionedCollector.php:243

Noticed recently on a production build of Silverstripe 5.1.  Have not yet determined the cause, but reporting it here for discussion.

A quick workaround is to disable the VersionedCollector from being processed

**Comment by elkebe** [comment]
Am getting the exact same error. Using SS5.2, php 8.3.
